Repository witseie-elen4010/2023-group-lab-005, pull requests merged in 2023-05, with the labels that each got.

#9 2-create-landing-page
  src/public/images/landingPage.svg
  src/public/images/loggo.png
  src/public/styles/LandingPage.css
  src/public/styles/footer.css
  src/server.js
  src/views/LandingPage.ejs
  src/views/Partials/footer.ejs
  src/views/Partials/header.ejs
Labels: developer-sized-story

#11 6 student account sign in
  src/__test__/register.test.js
  src/controllers/auth/studentController.js
  src/models/studentModel.js
  src/package-lock.json
  src/package.json
  src/public/styles/LandingPage.css
  src/public/styles/signin.css
  src/routes/studentRouter.js
  src/server.js
  src/views/Partials/signInPage.ejs
  src/views/studentDashboard.ejs
  src/views/studentSignIn.ejs
Labels: user-story, 2

#12 7 lecturers account creation
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/controllers/auth/studentController.js
  src/models/lecturerModel.js
  src/routes/lecturerRouter.js
  src/server.js
  src/views/lecturerRegister.ejs
  src/views/studentRegister.ejs
Labels: user-story, 3

#13 7 lecturers account creation
  src/__test__/register.test.js
  src/controllers/auth/studentController.js
  src/routes/studentRouter.js
  src/views/studentDashboard.ejs
Labels: user-story, 3

#17 Fixed the sign in bug
  src/__test__/register.test.js
  src/views/auth/student/signin.ejs
Labels: bug

#26 23 user account sign out functionality
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/package-lock.json
  src/package.json
  src/routes/lecturerRouter.js
  src/views/Partials/inAppheader.ejs
  src/views/Partials/inAppheaderLec.ejs
Labels: user-story, 3

#27 24 student activity log tracking
  .gitignore
  src/__test__/register.test.js
  src/controllers/auth/studentController.js
  src/controllers/logController.js
  src/models/logModel.js
  src/routes/logRouter.js
  src/server.js
  src/views/Partials/inAppheader.ejs
  src/views/view.ejs
Labels: user-story

#29 Fixed testing bug
  src/__test__/register.test.js
Labels: bug

#32 Fixed a test Bug
  src/__test__/register.test.js
Labels: bug

#34 3 student scheduling a consultation
  src/__test__/register.test.js
  src/controllers/consultationController.js
  src/models/consultationModel.js
  src/models/lecturerModel.js
  src/public/styles/consultation.css
  src/routes/consultationRouter.js
  src/server.js
  src/views/Partials/inAppheader.ejs
  src/views/lecturerAvailability.ejs
Labels: user-story, 4

#36 25 lecturer activity log tracking
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/controllers/availabilityController.js
  src/controllers/logController.js
  src/views/Partials/inAppheaderLec.ejs
Labels: user-story

#37 19 group selection for student consultations
  Documentation/ADRs/ADR3.md
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/controllers/auth/studentController.js
  src/controllers/consultationController.js
  src/routes/consultationRouter.js
  src/server.js
  src/views/Partials/inAppheader.ejs
  src/views/studentDashboard.ejs
Labels: user-story

#38 22-student-consultation-cancellation-and-dashboard-update
  src/__test__/register.test.js
  src/controllers/consultationController.js
  src/routes/consultationRouter.js
  src/views/studentDashboard.ejs
Labels: user-story, 4

#45 18 lecturer dashboard for upcoming consultations
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/controllers/consultationController.js
  src/routes/consultationRouter.js
  src/views/Partials/inAppheaderLec.ejs
  src/views/SetLecturerAvailability.ejs
  src/views/lecturerDashboard.ejs
  src/views/lecturerSignIn.ejs
  src/views/studentDashboard.ejs
Labels: user-story, 3

#48 20 canceling lecturer consultations
  src/__test__/register.test.js
  src/controllers/availabilityController.js
  src/controllers/consultationController.js
  src/routes/consultationRouter.js
  src/routes/lecturerRouter.js
  src/views/Partials/inAppheaderLec.ejs
  src/views/SetLecturerAvailability.ejs
  src/views/lecturerDashboard.ejs
Labels: user-story, 3

#46 44 secure password storage
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/controllers/auth/studentController.js
  src/models/studentModel.js
  src/package-lock.json
  src/package.json
Labels: security, user-story, 4

#50 42 student notification for consultation changes
  src/__test__/register.test.js
  src/controllers/consultationController.js
  src/views/SetLecturerAvailability.ejs
  src/views/lecturerDashboard.ejs
Labels: user-story, 4

#52 Update package.json
  package.json
Labels: bug

#55 Fixing coverage
  .github/workflows/main_consultify.yml
Labels: bug

#59 Fixed path for lcov.info
  .github/workflows/main_consultify.yml
Labels: bug

#60 43 user password reset
  src/__test__/register.test.js
  src/controllers/auth/lecturerController.js
  src/controllers/auth/studentController.js
  src/package-lock.json
  src/package.json
  src/routes/lecturerRouter.js
  src/routes/studentRouter.js
  src/views/auth/lecturer/newPassword.ejs
  src/views/auth/lecturer/resetPassword.ejs
  src/views/auth/student/newPassword.ejs
  src/views/auth/student/resetPassword.ejs
Labels: user-story, 3

#62 Fixing structure of .yml file
  .github/workflows/main_consultify.yml
Labels: bug

#64 40 lecturer consultation reminder
  package-lock.json
  package.json
  src/__test__/register.test.js
  src/server.js
Labels: user-story

#65 39 student consultation reminder
  src/controllers/notificationController.js
  src/server.js
Labels: user-story

#66 Added playwright testing framework
  src/.github/workflows/playwright.yml
  src/.gitignore
  src/e2e/example.spec.ts
  src/package-lock.json
  src/package.json
  src/playwright.config.js
  src/tests/e2e.ts
Labels: documentation

#67 56 implement user management interface
  src/__test__/register.test.js
  src/controllers/auth/adminController.js
  src/e2e/example.spec.ts
  src/models/adminModel.js
  src/package-lock.json
  src/package.json
  src/playwright.config.js
  src/routes/adminRouter.js
  src/server.js
  src/tests/e2e.ts
  src/views/Partials/header.ejs
  src/views/adminDashboard.ejs
  src/views/auth/admin/signin.ejs
Labels: user-story

#69 57 develop activity logging mechanism
  src/__test__/register.test.js
  src/controllers/availabilityController.js
  src/controllers/logController.js
  src/routes/logRouter.js
  src/views/Partials/inAppheaderAdmin.ejs
  src/views/SetLecturerAvailability.ejs
  src/views/adminDashboard.ejs
  src/views/allLogs.ejs
  src/views/lecturerDashboard.ejs
  src/views/studentDashboard.ejs
Labels: user-story

#71 Fixed the logger-bug
  src/controllers/auth/adminController.js
  src/controllers/availabilityController.js
  src/controllers/consultationController.js
  src/controllers/logController.js
  src/routes/logRouter.js
  src/views/Partials/inAppheaderLec.ejs
  src/views/studentDashboard.ejs
  src/views/viewLec.ejs
Labels: bug

#73 Added retrospective.md and fixed the lecturer dashboard
  Documentation/Sprint 3/Sprint3_retrospective.md
  src/views/lecturerDashboard.ejs
Labels: bug, documentation

#68 63 exploring playwright e2e testing
  .github/workflows/playwright.yml
  src/.env
  src/.gitignore
  src/playwright.config.js
  src/tests/E2E.spec.ts
Labels: bug, documentation
